### ISSUE TITLE
cmake fails to find libmagic，and already installed libmagic-dev

### ISSUE THREAD

**Issue by zjutsonggz** [robertogerson/dibr-player#1]
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   program_options
CMake Error at CMakeLists.txt:11 (find_package):
  By not providing "FindLibMagic.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "LibMagic",
  but CMake did not find one.

  Could not find a package configuration file provided by "LibMagic" with any
  of the following names:

    LibMagicConfig.cmake
    libmagic-config.cmake

  Add the installation prefix of "LibMagic" to CMAKE_PREFIX_PATH or set
  "LibMagic_DIR" to a directory containing one of the above files.  If
  "LibMagic" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring incomplete, errors occurred!
See also "/usr/local/dibr-player-master/build/CMakeFiles/CMakeOutput.log".
See also "/usr/local/dibr-player-master/build/CMakeFiles/CMakeError.log".

**Comment by robertogerson** [comment]
Hi @zjutsonggz.  Did you cloned the repository with
``
git clone --recursive https://github.com/robertogerson/dibr-player.git
``
or used git submodule init/update to update the CMakeModules submodule ?

If not, this may be the problem.  The FindLibMagic.cmake file is in the submodule.  (Probably, this info should be in the README.md file).  If you did so, let me know, that I will check if it is another problem.

**Comment by zjutsonggz** [comment]
Oh, yes, Thankyou!!!
I executed  ./dibr-player-cpu ../samples/images/flower04.jpg is OK , 
But when I executed ./dibr-player-opencl ../samples/images/flower04.jpg will failed and point out :
1920x1080
terminate called after throwing an instance of 'boost::exception_detail::clone_impl&lt;boost::exception_detail::error_info_injector<boost::bad_any_cast> &gt;'
  what():  boost::bad_any_cast: failed conversion using boost::any_cast
Aborted (core dumped)

**Comment by zjutsonggz** [comment]
Oh, yes,    @robertogerson.Thankyou!!!
I executed ./dibr-player-cpu ../samples/images/flower04.jpg is OK ,
But when I executed ./dibr-player-opencl ../samples/images/flower04.jpg will failed and point out :
1920x1080
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injectorboost::bad_any_cast >'
what(): boost::bad_any_cast: failed conversion using boost::any_cast
Aborted (core dumped)

**Comment by zjutsonggz** [comment]
@robertogerson Oh, yes, Thankyou!!!
I executed ./dibr-player-cpu ../samples/images/flower04.jpg is OK ,
But when I executed ./dibr-player-opencl ../samples/images/flower04.jpg will failed and point out :
1920x1080
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injectorboost::bad_any_cast >'
what(): boost::bad_any_cast: failed conversion using boost::any_cast
Aborted (core dumped)

**Comment by robertogerson** [comment]
Hi @zjutsonggz !
Sorry for the delay, but I have been very busy lately.  I added a new commit which will probably help you a little.  The dibr-player-cpu and the dibr-player-opencl receive a few different options and are behaving little different now (indeed the idea is soon to have only one program with a parameter --cpu or --opencl).

Thus, to get the dibr-player-opencl to run you should use the following:
```./dibr-player-opencl -i file.mp4 --opencl```

Also, you should be aware that (with my last commit) dibr-player-opencl receives a video+depth (texture side-by-side with the depth information).  Thus, you will not be able to run it with the flower.jpg sample.

Here are some samples you can use (you can download them and use as above):

https://www.youtube.com/watch?v=CD3W8JKGC8k
https://www.youtube.com/watch?v=8Ge4F0RB86k
https://www.youtube.com/watch?v=bMRxqkb7PN4

If you have some problem with the samples, let me know, that I can send you a link with them (or with other samples I use).

**Comment by zjutsonggz** [comment]
Oh, Thankyou verymuch! @robertogerson I am runing this Project on NVIDIA Jeston TX2 been installed CUDA 8.0, I think the OpenCL maybe not support.
