### ISSUE TITLE
Aborted (core dumped) upon resizing

### ISSUE THREAD

**Issue by 3togo** [robertogerson/dibr-player#4]
jc@jc-X230:~/git/dibr-player/build$ dibr-player-opencl ../samples/images/flower04.jpg 
1920x1080
clErr=0
Platform 0: Intel
Platform found : Intel

Selected Platform Vendor: Intel
Number of Devices Found 1
Device -->0 : Intel(R) HD Graphics IvyBridge M GT2
Device Version -->OpenCL 1.2 beignet 1.3
OpenCL version -->OpenCL C 1.2 beignet 1.3
max compute units -->16
Info: Found extension support ‘cl_khr_gl_sharing’!
Found GL Sharing Support!

Reading Kernel File ./convolution.cl

Build Log:

#Decode	Resize	Crop	Filter	DIBR	Show
OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /build/opencv-zcaJjh/opencv-3.2.0+dfsg/modules/imgproc/src/imgwarp.cpp, line 3492
terminate called after throwing an instance of 'cv::Exception'
  what():  /build/opencv-zcaJjh/opencv-3.2.0+dfsg/modules/imgproc/src/imgwarp.cpp:3492: error: (-215) ssize.width > 0 && ssize.height > 0 in function resize

Aborted (core dumped)
jc@jc-X230:~/git/dibr-player/build$

**Comment by robertogerson** [comment]
Hi @3togo , what do you mean about "upon resizing"?  Please take a look in this issue: https://github.com/robertogerson/dibr-player/issues/1
In special, the parameters for dibr-player-opencl should be: `./dibr-player-opencl -i file.mp4 --opencl`
If this does not should your problem, please let me know.

**Comment by 3togo** [comment]
many thanks. 

problem fixed
